# # docker-compose.yml
# version: '3.8'
# services:
#   # Frontend
#   frontend:
#     build: ./towyui
#     ports:
#       - "3000:3000"
#     volumes:
#       - ./towyui:/app
#       - /app/node_modules
#       - /app/.next
#     environment:
#       - NEXT_PUBLIC_API_URL=http://backend:4000

#   # Backend
#   backend:
#     build: ./towy-backend
#     ports:
#       - "4000:4000"
#     depends_on:
#       - postgres

#   # Database
#   postgres:
#     image: postgres:14
#     environment:
#       POSTGRES_USER: ${DB_USER}
#       POSTGRES_PASSWORD: ${DB_PASSWORD}
#       POSTGRES_DB: ${DB_NAME}